### ISSUE TITLE
ci.yml check fails

### ISSUE THREAD

**Issue by yanns** [djspiewak/sbt-github-actions#44]
Hi,

first, thanks for this plugin!
I'm trying to use it for sangria, and the check about `ci.yml` fails: https://github.com/sangria-graphql/sangria/pull/547/checks?check_run_id=1555592842
```
info] set current project to sangria-root (in build file:/home/runner/work/sangria/sangria/)
[error] java.lang.RuntimeException: ci.yml does not contain contents that would have been generated by sbt-github-actions; try running githubWorkflowGenerate
```

Running `sbt githubWorkflowGenerate` locally does not change this file.
I don't really know how to debug this.

**Comment by travisbrown** [comment]
I think the issue here is that if you run `githubWorkflowGenerate` for 2.12 it'll have a different value for `crossScalaVersions`, which will result in a different `ci.yml` (note that `githubWorkflowCheck` is only failing on 2.12). If you define the default Scala version in terms of `crossScalaVersions` (instead of the reverse) it should be fine:

```scala
ThisBuild / crossScalaVersions := Seq("2.12.11", "2.13.4")
ThisBuild / scalaVersion := crossScalaVersions.value.last
```

**Comment by yanns** [comment]
Thanks @travisbrown your suggestion is working! ❤️
