### ISSUE TITLE
githubWorkflowCheck failing when adjusting githubWorkflowScalaVersions

### ISSUE THREAD

**Issue by mdedetrich** [djspiewak/sbt-github-actions#70]
For some odd reason, if you remove a scala version to be tested by CI using `githubWorkflowScalaVersions`, specifically in my case

```scala
// Scala 2.10.7 seems to be causing issues with CI
ThisBuild / githubWorkflowScalaVersions -= "2.10.7"
```

and I commit this to a PR, `githubWorkflowCheck` ends up failing (specifically in the `ci.yml` spot where you have `strategy.matrix.scala`

You can find an example of this happening here https://github.com/iheartradio/ficus/pull/155, you can check the `Continuous Integration / Build and Test (ubuntu-latest, 2.13.6, adopt@1.8) (pull_request)` build failure in that PR.

**Comment by djspiewak** [comment]
My guess is that something isn't using this setting when it really should have been! Will add a test and fix.

**Comment by djspiewak** [comment]
I wasn't able to reproduce this. However I was able to identify the issue in the PR you linked. I believe if you apply the fix I suggested, your build should work again. Tldr sbt changes `scalaVersion` all the time, and so you should be careful about what you *derive* from it. `crossScalaVersions` is particularly bad because it creates a cycle, which has weird consequences.
